version: '2'
services:
  chipy-db:
    image: postgres
    container_name: chipy-db
    env_file:
      - docker/docker.env
  chipy-web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: chipy-web
    env_file:
      - docker/docker.env
    ports:
      - "8000:8000"
    volumes:
      - .:/var/app/
